resolver: lts-11.17
packages:
- .
extra-deps:
    - acid-state-0.14.3
    - distribution-1.1.1.0
    - github: tsahyt/yak
      commit: e122d2c0dcb25387d44ab6195e9076e79a6f782c 
    - github: tsahyt/voco
      commit: 1bd635dfd958ad593bee8d9811ff993dcdd859a8

# docker build
image:
  containers:
    - base: "fpco/haskell-scratch"
      name: "tsahyt/botnet2"
      entrypoints:
        - botnet2
