resolver: lts-11.22
packages:
- .
extra-deps:
    - acid-state-0.14.3
    - distribution-1.1.1.0
    - github: tsahyt/yak
      commit: e122d2c0dcb25387d44ab6195e9076e79a6f782c 
    - github: tsahyt/voco
      commit: 63ed4d451730616b14aed285ccb95d0d557d153d
docker:
    enable: false
    image: "tsahyt/centos-stack:ghc-8.2.2"
