root:
    - tsahyt
    - tsahyt
    - user/tsahyt
paths:
    db-root: "./state"
    citation-root: "./etc/quotes"
    markov-root: "./etc/markov"
connection:
    hostname: "irc.snoonet.org"
    port: 6697
    ssl: true
    pwd: null
    nick: "botnet"
    user: "botnet"
channels:
    - "#voco-example"
keys:
    alpha-vantage: "DEMO"
    wolfram-alpha: null
